<?php

declare(strict_types=1);

/**
 * The first guard `tools/gen-docs.php` has ever had (E549).
 *
 * WHY IT MATTERS MORE THAN AN ORDINARY MISSING TEST. This generator WRITES
 * every `docs/lib/<slug>.html` in the tree, and both AGENTS.md and CLAUDE.md
 * instruct every contributor and every agent never to hand-edit its output:
 * "generated by tools/gen-docs.php … never hand-edit". So a defect here cannot
 * be worked around downstream by definition — the only sanctioned repair for a
 * wrong page is to re-run the thing that produced it.
 *
 * AND ITS OWN DRIFT GUARD RUNS NOWHERE. MEASURED at the commit this file was
 * written: `--check` is described in the script's header as "a CI drift guard",
 * and `grep -rn gen-docs .github/` matches nothing. `pages.yml` uploads `docs/`
 * verbatim to GitHub Pages on every push to master, so a hand-edit to a
 * generated page publishes to the public site and survives until the next
 * unrelated `gen-docs.php` run silently reverts it. This file is half the fix;
 * the `docs-links` job now runs `--check` for the other half.
 *
 * HOW IT DRIVES THE SCRIPT. As a subprocess against a throwaway fixture root,
 * via `SUGARCRAFT_GEN_DOCS_ROOT` — the same env override
 * `tools/check-path-repos.php` already carried, added to this script for the
 * same reason. Testing observable process behaviour rather than the individual
 * functions is not a shortcut here: the script is top-level code that ends in
 * `exit()`, so `require`-ing it to unit-test `parse_matchups()` would run the
 * whole generator against the real `docs/` and then kill the test runner.
 *
 * THE FIXTURE COUNTS ARE DELIBERATELY NOT THE REAL ONES. The real split is
 * 39/19; the fixture is 23 libraries / 4 apps. A guard whose expectations
 * happen to equal the production values passes just as well when the counts are
 * hardcoded, which is the defect class `patch_index_counts()` exists to close.
 * 23 and 27 are also both hyphenated when spelled out, so `number_to_words()`
 * is exercised on its compound branch rather than its lookup-table branch.
 */

namespace SugarCraft\Tools\Tests;

require_once __DIR__ . '/_bootstrap.php';

use PHPUnit\Framework\TestCase;

final class GenDocsTest extends TestCase
{
    use TmpTree;

    /** MATCHUPS rows beyond the two that get pages, purely to move the counts. */
    private const FILLER_LIBS = 21;

    protected function setUp(): void
    {
        $this->tmpDir = $this->makeTmpTree('gen_docs_test_');
    }

    protected function tearDown(): void
    {
        if ($this->tmpDir !== '') {
            $this->removeDir($this->tmpDir);
        }
    }

    // -----------------------------------------------------------------
    // Fixture construction
    // -----------------------------------------------------------------

    /**
     * A monorepo root containing only what the generator reads: docs/MATCHUPS.md,
     * docs/_data/, docs/lib/ and docs/index.html.
     *
     * @param list<string> $dataSlugs slugs to give a _data entry (and so a page)
     */
    private function makeFixtureRoot(array $dataSlugs = ['fixture-alpha', 'fixture-appy']): string
    {
        $root = $this->tmpDir;
        \mkdir($root . '/docs/_data', 0777, true);
        \mkdir($root . '/docs/lib', 0777, true);
        \file_put_contents($root . '/docs/MATCHUPS.md', $this->matchupsFixture());
        \file_put_contents($root . '/docs/index.html', $this->indexFixture());
        foreach ($dataSlugs as $slug) {
            $this->writeData($root, $slug);
        }
        return $root;
    }

    /**
     * 23 library rows and 4 app rows, plus one library row inside an HTML
     * comment. The commented row is the whole point of the block: MATCHUPS
     * really does carry a commented-out ConPTY-Windows row, and if the parser
     * stopped skipping comments the counts would silently go up by one.
     */
    private function matchupsFixture(): string
    {
        $md = "# Fixture matchups\n\n## Charmbracelet libraries\n\n| Upstream | Subdir |\n|---|---|\n";
        $md .= "| alpha | `fixture-alpha/` |\n";
        for ($i = 1; $i <= self::FILLER_LIBS + 1; $i++) {
            $md .= "| filler$i | `fixture-filler$i/` |\n";
        }
        $md .= "\n<!--\n| todo | `fixture-hidden/` | not ported yet |\n-->\n";
        $md .= "\n## Apps\n\n| Upstream | Subdir |\n|---|---|\n";
        $md .= "| appy | `fixture-appy/` |\n";
        for ($i = 1; $i <= 3; $i++) {
            $md .= "| appfill$i | `fixture-appfill$i/` |\n";
        }
        return $md;
    }

    /** 23 libraries, 4 apps, 27 packages — what matchupsFixture() describes. */
    private function expectedCounts(): array
    {
        return ['lib' => 2 + self::FILLER_LIBS, 'app' => 4, 'total' => 6 + self::FILLER_LIBS];
    }

    /**
     * index.html with every count token present and every one of them WRONG,
     * in both the numeral and the spelled-out shapes the patcher handles.
     */
    private function indexFixture(): string
    {
        return <<<'HTML'
        <!doctype html>
        <html lang="en"><head>
        <meta name="description" content="SugarCraft: 7 libraries and 2 apps (9 packages) of PHP TUI.">
        <meta property="og:description" content="SugarCraft: 7 libraries and 2 apps (9 packages) of PHP TUI.">
        <script type="application/ld+json">{"description":"7 libraries and 2 apps (9 packages)"}</script>
        </head><body>
        <p class="hero-sub">A complete PHP TUI ecosystem — seven libraries and two apps (nine packages total).</p>
        <div class="stats">
        <span class="num">7</span><span class="label">libraries</span>
        <span class="num">2</span><span class="label">apps</span>
        </div>
        <h2>Seven libraries, one ecosystem.</h2>
        <h2>Two apps built on the stack.</h2>
        </body></html>
        HTML;
    }

    private function writeData(string $root, string $slug): void
    {
        $meta = [
            'title'         => "$slug — SugarCraft",
            'description'   => "Fixture description for $slug.",
            'ogTitle'       => "$slug",
            'ogDescription' => "Fixture og description for $slug.",
            'emoji'         => '🍬',
            'displayName'   => 'FixtureName',
            'tagline'       => 'A fixture tagline.',
            'phpVersion'    => '8.3+',
            'detailMeta'    => $this->detailMetaFixture(),
        ];
        \file_put_contents(
            "$root/docs/_data/$slug.json",
            \json_encode($meta, \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES | \JSON_UNESCAPED_UNICODE | \JSON_THROW_ON_ERROR) . "\n"
        );
        \file_put_contents("$root/docs/_data/$slug.body.html", $this->bodyFixture($slug));
    }

    /**
     * Three chips: a bare "port of" label, a "port of" label whose URL carries a
     * `tree/<branch>/` segment, and a special accent chip with no "port of" at
     * all. The third is the one that makes the first two mean something — a
     * normalizer that rewrote every accent chip would pass a fixture containing
     * only the first two.
     */
    private function detailMetaFixture(): string
    {
        return '          <span class="tag-chip accent">port of <a href="https://github.com/charmbracelet/harmonica" style="color: inherit;">harmonica</a></span>' . "\n"
            . '          <span class="tag-chip accent">port of <a href="https://github.com/charmbracelet/x/tree/main/ansi" style="color: inherit;">x/ansi</a></span>' . "\n"
            . '          <span class="tag-chip accent">pioneering</span>';
    }

    /**
     * A body carrying BOTH a self link (must be rewritten main→master) and an
     * upstream link that also says `tree/main` (must NOT be). Rule 11: a fixture
     * whose alphabet contains only the positive case cannot tell a correctly
     * scoped rewrite from a blanket one.
     */
    private function bodyFixture(string $slug): string
    {
        return '<p class="lede" style="margin-top: 28px;">Fixture lede for ' . $slug . ".</p>\n"
            . '<p>See <a href="https://github.com/sugarcraft/' . $slug . '/blob/main/README.md">ours</a>'
            . ' and <a href="https://github.com/charmbracelet/x/tree/main/ansi">theirs</a>.</p>' . "\n";
    }

    // -----------------------------------------------------------------
    // Invocation
    // -----------------------------------------------------------------

    /**
     * @param list<string> $args
     * @return array{exit:int,output:string}
     */
    private function runScript(string $root, array $args = []): array
    {
        $cmd = 'SUGARCRAFT_GEN_DOCS_ROOT=' . \escapeshellarg($root)
            . ' ' . \escapeshellcmd(\PHP_BINARY)
            . ' ' . \escapeshellarg(__DIR__ . '/../gen-docs.php');
        foreach ($args as $arg) {
            $cmd .= ' ' . \escapeshellarg($arg);
        }
        $output = [];
        $exitCode = 0;
        \exec($cmd . ' 2>&1', $output, $exitCode);
        return ['exit' => $exitCode, 'output' => \implode("\n", $output)];
    }

    private function page(string $root, string $slug): string
    {
        $path = "$root/docs/lib/$slug.html";
        $this->assertFileExists($path);
        return (string) \file_get_contents($path);
    }

    // -----------------------------------------------------------------
    // Generation
    // -----------------------------------------------------------------

    public function testGenerationWritesOnePagePerDataSlugAndReportsTheMatchupsSplit(): void
    {
        $root = $this->makeFixtureRoot();
        $c = $this->expectedCounts();

        $r = $this->runScript($root);
        $this->assertSame(0, $r['exit'], $r['output']);
        $this->assertStringContainsString("libraries: {$c['lib']}, apps: {$c['app']}", $r['output']);

        $this->assertFileExists("$root/docs/lib/fixture-alpha.html");
        $this->assertFileExists("$root/docs/lib/fixture-appy.html");
        // A MATCHUPS row with no _data entry gets no page — the data store, not
        // MATCHUPS, decides which pages exist.
        $this->assertFileDoesNotExist("$root/docs/lib/fixture-filler1.html");
    }

    /**
     * The breadcrumb count is DERIVED from the MATCHUPS split, and which table a
     * slug sits in decides whether it says libraries or apps.
     *
     * This is the assertion the commented-out MATCHUPS row is really aimed at:
     * un-skip HTML comments and the library count moves 23 → 24 here.
     */
    public function testTheBreadcrumbCarriesTheDerivedCountAndTheCorrectPlural(): void
    {
        $root = $this->makeFixtureRoot();
        $c = $this->expectedCounts();
        $this->runScript($root);

        $this->assertStringContainsString(
            '<a href="../#libraries">← All ' . $c['lib'] . ' libraries</a>',
            $this->page($root, 'fixture-alpha')
        );
        $this->assertStringContainsString(
            '<a href="../#apps">← All ' . $c['app'] . ' apps</a>',
            $this->page($root, 'fixture-appy')
        );
    }

    /**
     * BOTH POLARITIES of the self-link rewrite, in one page (rule 11).
     */
    public function testSelfLinksAreRetargetedToMasterAndUpstreamLinksAreNot(): void
    {
        $root = $this->makeFixtureRoot();
        $this->runScript($root);
        $html = $this->page($root, 'fixture-alpha');

        $this->assertStringContainsString('https://github.com/sugarcraft/fixture-alpha/blob/master/README.md', $html);
        $this->assertStringNotContainsString('https://github.com/sugarcraft/fixture-alpha/blob/main/', $html);
        $this->assertStringContainsString('https://github.com/charmbracelet/x/tree/main/ansi', $html);
    }

    /**
     * BOTH POLARITIES of the port-label normalization: bare labels become
     * owner/repo, a `tree/<branch>/` segment is dropped, and an accent chip that
     * is not a "port of" chip is untouched.
     */
    public function testPortLabelsAreNormalizedAndOtherAccentChipsAreLeftAlone(): void
    {
        $root = $this->makeFixtureRoot();
        $this->runScript($root);
        $html = $this->page($root, 'fixture-alpha');

        $this->assertStringContainsString('style="color: inherit;">charmbracelet/harmonica</a>', $html);
        $this->assertStringContainsString('style="color: inherit;">charmbracelet/x/ansi</a>', $html);
        $this->assertStringContainsString('<span class="tag-chip accent">pioneering</span>', $html);
    }

    /** The h2 splits a leading non-ASCII run off as the emoji. */
    public function testTheEmojiAndDisplayNameAreRecombinedInTheHeading(): void
    {
        $root = $this->makeFixtureRoot();
        $this->runScript($root);
        $this->assertStringContainsString('<h2>🍬 FixtureName</h2>', $this->page($root, 'fixture-alpha'));
    }

    // -----------------------------------------------------------------
    // index.html counts
    // -----------------------------------------------------------------

    /**
     * Every count token on the homepage is rewritten from the MATCHUPS split,
     * in both numeral and spelled-out form, and a second run is a no-op.
     *
     * The fixture arrives with every one of these WRONG (7/2/9, seven/two/nine),
     * so an assertion here cannot be satisfied by a patcher that does nothing.
     */
    public function testTheHomepageCountTokensAreRewrittenFromMatchupsAndThePatchIsIdempotent(): void
    {
        $root = $this->makeFixtureRoot();
        $c = $this->expectedCounts();
        $this->runScript($root);
        $index = (string) \file_get_contents("$root/docs/index.html");

        // Numerals: description, og:description, JSON-LD, both .stat spans.
        $this->assertSame(
            3,
            \substr_count($index, "{$c['lib']} libraries and {$c['app']} apps"),
            'expected all three numeral count phrases rewritten'
        );
        $this->assertStringContainsString("({$c['total']} packages)", $index);
        $this->assertStringContainsString('<span class="num">' . $c['lib'] . '</span><span class="label">libraries</span>', $index);
        $this->assertStringContainsString('<span class="num">' . $c['app'] . '</span><span class="label">apps</span>', $index);

        // Spelled out: hero prose and both section headings. 23 and 27 are
        // hyphenated, so this covers number_to_words()'s compound branch.
        $this->assertStringContainsString('ecosystem — twenty-three libraries and four apps (twenty-seven packages total)', $index);
        $this->assertStringContainsString('<h2>Twenty-three libraries, one ecosystem.</h2>', $index);
        $this->assertStringContainsString('<h2>Four apps built on the stack.</h2>', $index);

        // Nothing of the wrong values survives anywhere.
        $this->assertStringNotContainsString('7 libraries and 2 apps', $index);
        $this->assertStringNotContainsString('seven libraries', $index);

        // Idempotent: the patch matches count POSITIONS, not values, which is
        // the property that makes --check a reliable drift guard.
        $this->runScript($root);
        $this->assertSame($index, (string) \file_get_contents("$root/docs/index.html"));
    }

    // -----------------------------------------------------------------
    // --check
    // -----------------------------------------------------------------

    /**
     * --check in BOTH polarities, in one test, on one tree (rules 15 and 25).
     *
     * A guard that only ever asserts "--check says ok" passes identically when
     * --check has been mutated to return 0 unconditionally. So the clean verdict
     * is taken first, then a single byte of one page is changed and the SAME
     * invocation must go red and NAME the page.
     */
    public function testCheckPassesOnGeneratedPagesAndFailsNamingAHandEditedOne(): void
    {
        $root = $this->makeFixtureRoot();
        $this->runScript($root);

        $clean = $this->runScript($root, ['--check']);
        $this->assertSame(0, $clean['exit'], $clean['output']);
        $this->assertStringContainsString('ok: all 2 pages', $clean['output']);

        $path = "$root/docs/lib/fixture-alpha.html";
        \file_put_contents($path, \str_replace('A fixture tagline.', 'HAND EDITED', (string) \file_get_contents($path)));

        $dirty = $this->runScript($root, ['--check']);
        $this->assertSame(1, $dirty['exit'], 'a hand-edited page must fail --check');
        $this->assertStringContainsString('drift: fixture-alpha.html differs', $dirty['output']);
        $this->assertStringContainsString('1 page(s) out of sync', $dirty['output']);
        // The other page is not implicated.
        $this->assertStringNotContainsString('drift: fixture-appy.html', $dirty['output']);
    }

    /**
     * index.html drift is a SEPARATE verdict from page drift, and a hand-edit
     * that only touches the homepage counts must still be caught.
     */
    public function testCheckFailsOnHomepageCountDriftAloneWithEveryPageInSync(): void
    {
        $root = $this->makeFixtureRoot();
        $this->runScript($root);
        $this->assertSame(0, $this->runScript($root, ['--check'])['exit']);

        $index = "$root/docs/index.html";
        \file_put_contents($index, \str_replace(
            '<span class="num">23</span><span class="label">libraries</span>',
            '<span class="num">99</span><span class="label">libraries</span>',
            (string) \file_get_contents($index)
        ));

        $r = $this->runScript($root, ['--check']);
        $this->assertSame(1, $r['exit'], 'homepage count drift must fail --check');
        $this->assertStringContainsString('drift: index.html counts differ from computed 23/4', $r['output']);
        $this->assertStringNotContainsString('drift: fixture-alpha.html', $r['output']);
    }

    /** --check must not write. A drift guard that repairs the drift reports nothing. */
    public function testCheckDoesNotWriteToTheTree(): void
    {
        $root = $this->makeFixtureRoot();
        $this->runScript($root);

        $path = "$root/docs/lib/fixture-alpha.html";
        $edited = \str_replace('A fixture tagline.', 'HAND EDITED', (string) \file_get_contents($path));
        \file_put_contents($path, $edited);

        $this->runScript($root, ['--check']);
        $this->assertSame($edited, (string) \file_get_contents($path), '--check must leave the tree untouched');
    }

    // -----------------------------------------------------------------
    // --extract
    // -----------------------------------------------------------------

    /**
     * generate → extract → generate is a fixed point.
     *
     * The strongest single property this script has, because it pins
     * extract_one() and generate_one() against each other: any field the
     * generator emits but the extractor cannot read back is content silently
     * lost the next time someone runs --extract.
     */
    public function testExtractRoundTripsBackToByteIdenticalPages(): void
    {
        $root = $this->makeFixtureRoot();
        $this->runScript($root);
        $first = $this->page($root, 'fixture-alpha');

        $e = $this->runScript($root, ['--extract']);
        $this->assertSame(0, $e['exit'], $e['output']);
        $this->assertStringContainsString('extracted 2 page(s)', $e['output']);

        $this->runScript($root);
        $this->assertSame($first, $this->page($root, 'fixture-alpha'));
        $this->assertSame(0, $this->runScript($root, ['--check'])['exit']);
    }

    /**
     * Head markup that legitimately diverges from the shared template survives a
     * round trip, rather than being normalized away.
     *
     * The real case is candy-core's skip-link + ARIA nav + twitter:image. If
     * prefixOverride stopped being captured, the accessibility markup on that
     * page would vanish on the next regen with no diff to explain it.
     */
    public function testDivergentHeadMarkupIsPreservedThroughExtractAndRegenerate(): void
    {
        $root = $this->makeFixtureRoot();
        $this->runScript($root);

        $path = "$root/docs/lib/fixture-alpha.html";
        $extra = '<meta name="twitter:image" content="https://example.invalid/x.png">';
        \file_put_contents($path, \str_replace(
            '<meta name="twitter:card" content="summary_large_image">',
            '<meta name="twitter:card" content="summary_large_image">' . "\n" . $extra,
            (string) \file_get_contents($path)
        ));

        $this->runScript($root, ['--extract']);
        $json = (string) \file_get_contents("$root/docs/_data/fixture-alpha.json");
        $this->assertStringContainsString('prefixOverride', $json, 'divergent head markup must be stored');

        $this->runScript($root);
        $this->assertStringContainsString($extra, $this->page($root, 'fixture-alpha'));

        // And the page that did NOT diverge must not have acquired an override —
        // otherwise every page would be pinned to whatever it looked like at the
        // last extract, and the shared template would stop being shared.
        $this->assertStringNotContainsString(
            'prefixOverride',
            (string) \file_get_contents("$root/docs/_data/fixture-appy.json")
        );
    }

    // -----------------------------------------------------------------
    // Failure modes
    // -----------------------------------------------------------------

    public function testAnUnknownModeIsRejectedWithUsageAndExitTwo(): void
    {
        $root = $this->makeFixtureRoot();
        $r = $this->runScript($root, ['--regenerate']);
        $this->assertSame(2, $r['exit']);
        $this->assertStringContainsString('usage: gen-docs.php [--extract|--check]', $r['output']);
        // And it did so before writing anything.
        $this->assertFileDoesNotExist("$root/docs/lib/fixture-alpha.html");
    }

    public function testAnEmptyDataStoreFailsWithTheExtractHintRatherThanWritingNothingQuietly(): void
    {
        $root = $this->makeFixtureRoot([]);
        $r = $this->runScript($root);
        $this->assertSame(1, $r['exit']);
        $this->assertStringContainsString('no data store found', $r['output']);
    }

    /**
     * A _data slug with no MATCHUPS row is a warning and a skip, not a fatal —
     * but it must still SAY so. Rule 14: a generator that silently ignores an
     * input it cannot classify has a hole shaped like the next defect.
     */
    public function testADataSlugWithNoMatchupsRowIsReportedAndSkippedWithoutFailingTheRun(): void
    {
        $root = $this->makeFixtureRoot(['fixture-alpha', 'fixture-appy', 'fixture-orphan']);
        $r = $this->runScript($root);

        $this->assertSame(0, $r['exit'], $r['output']);
        $this->assertStringContainsString("warning: fixture-orphan has no MATCHUPS row", $r['output']);
        $this->assertFileDoesNotExist("$root/docs/lib/fixture-orphan.html");
        $this->assertFileExists("$root/docs/lib/fixture-alpha.html");
    }

    public function testAnUnresolvableRootOverrideIsRejectedWithExitTwo(): void
    {
        $r = $this->runScript($this->tmpDir . '/no-such-dir');
        $this->assertSame(2, $r['exit']);
        $this->assertStringContainsString('SUGARCRAFT_GEN_DOCS_ROOT is not a valid path', $r['output']);
    }
}
